name: Backend ( FastAPI ) CI

on:
  push:
    branches-ignore: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  lint-and-healthcheck:
    uses: ./.github/workflows/backend-deploy.yml
    secrets: inherit
