name: Backend Deploy

on:
  workflow_call:

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyLint
        continue-on-error: true
        run: |
          cd backend
          pylint app.py controllers/ usecases/ --exit-zero

  deploy:
    needs: lint-code
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        check-latest: true
    
    - name: Package Lambda function
      run: |
        cd backend
        pip install --upgrade pip
        mkdir -p lib
        pip install -t lib -r requirements.txt
        ( cd lib; zip ../aws_lambda.zip -r .)
        zip -r aws_lambda.zip app.py controllers models repositories usecases

    - name: Install AWS CDK CLI
      run: |
        npm install -g aws-cdk@latest
        cdk --version

    - name: Deploy to Lambda
      run: |
        cd infra
        npm install
        # Update your Lambda function name here
        cdk deploy prod-StatelessStack --require-approval never

    - name: Verify Deployment
      run: |
        aws lambda get-function --function-name prod-Lambda-SampleFunction
