name: Backend ( FastAPI ) CI

on:
  push:
    branches-ignore: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  lint_and_healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyLint
        run: |
          pylint app.py controllers/ models/ repositories/ usecases/

      - name: Launch Uvicorn in background
        run: |
          uvicorn app:app --host 127.0.0.1 --port 8000 &
          # wait a few seconds for startup
          sleep 3

      - name: Check server health with curl
        run: |
          curl --fail http://127.0.0.1:8000/ || ( echo "Health check failed" && exit 1 )
      
      - name: Shut down background server
        run: |
          kill $(lsof -t -i:8000) || echo "No server to kill"
