name: Backend deploy to Dev Environment

on:
  workflow_call:

jobs:
  backend-ci-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          cd infra/lambdaFunctions/backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyLint
        continue-on-error: true
        run: |
          pylint app.py

  backend-deploy-dev:
    needs: backend-ci-dev
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        check-latest: true
    
    - name: Package Lambda function
      run: |
        cd infra/lambdaFunctions/backend
        pip install --upgrade pip
        mkdir lib
        pip install \
          --platform manylinux2014_x86_64 \
          --implementation cp \
          --python-version 3.13 \
          --only-binary=:all: \
          -t lib/ \
          -r requirements.txt
        (cd lib && zip -r ../aws_lambda.zip .)
        zip -r aws_lambda.zip app.py controllers models repositories usecases services utils

    - name: Install AWS CDK CLI
      run: |
        npm install -g aws-cdk@latest
        cdk --version

    - name: Deploy to Lambda
      run: |
        cd infra
        npm install
        # Update your Lambda function name here
        cdk deploy dev-StatelessStack --require-approval never

    - name: Verify Deployment
      run: |
        aws lambda get-function --function-name dev-Lambda-SampleFunction
