name: Backend Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Package Lambda function
      run: |
        cd backend
        pip install -t lib -r requirements.txt
        ( cd lib; zip ../aws_lambda.zip -r .)
        zip aws_lambda.zip -u app.py

    - name: Deploy to Lambda
      run: |
        cd backend
        # Update your Lambda function name here
        aws lambda update-function-code \
          --function-name prod-Lambda-SampleFunction\
          --zip-file fileb://aws_lambda.zip

    - name: Verify Deployment
      run: |
        aws lambda get-function --function-name prod-Lambda-SampleFunction
