name: Backend Deploy

on:
  workflow_call:

jobs:
  lint_and_healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyLint
        run: |
          pylint app.py controllers/ models/ repositories/ usecases/

      - name: Launch Uvicorn in background
        run: |
          uvicorn app:app --host 127.0.0.1 --port 8000 &
          # wait a few seconds for startup
          sleep 3

      - name: Check server health with curl
        run: |
          curl --fail http://127.0.0.1:8000/ || ( echo "Health check failed" && exit 1 )
      
      - name: Shut down background server
        run: |
          kill $(lsof -t -i:8000) || echo "No server to kill"

  deploy:
    needs: lint_and_healthcheck
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Package Lambda function
      run: |
        cd backend
        pip install --upgrade pip
        mkdir -p lib
        pip install -t lib -r requirements.txt
        ( cd lib; zip ../aws_lambda.zip -r .)
        zip -r aws_lambda.zip app.py controllers models repositories usecases

    - name: Deploy to Lambda
      run: |
        cd backend
        # Update your Lambda function name here
        aws lambda update-function-code \
          --function-name prod-Lambda-SampleFunction\
          --zip-file fileb://aws_lambda.zip

    - name: Verify Deployment
      run: |
        aws lambda get-function --function-name prod-Lambda-SampleFunction
