name: Infrastracture ( AWS )  CI

on:
  push:
    branches-ignore: [ main ]
    paths:
     - 'infra/**'

  pull_request:
    paths:
      - 'infra/**'

jobs:
  lint-and-build:
    uses: ./.github/workflows/infra-deploy.yml
    secrets: inherit
